### ISSUE TITLE
Rig cannot connect

### ISSUE THREAD

**Issue by coolsd** [joshuayabut/z-nomp#11]
ZEC:  Stratum  -  connecting  to  '139.162.*.*'  <139.162.*.*>  port  3032
ZEC:  Stratum  -  Connected  (139.162.*.*:3032)
Pool  sets  new  share  target:  0x006e5846  (diff:  593H)
ZEC:  Share  rejected  (120328  ms)!
ZEC:  Authorization  failed
:  {"id":2,"result":false,"error":null}

**Comment by joshuayabut** [comment]
Can you post some of the debug from the server too? My initial thoughts are that maybe the username isn't a valid t_address.

**Comment by coolsd** [comment]
To find the reason,   works can not bring name.

t1d2VRQHwM8kRyHzfzf29cg7kuSE1dU5fWe.A01

**Comment by coolsd** [comment]
Pool Hashrate display is not correct. 877H/s pool display 209M.

**Comment by joshuayabut** [comment]
Can you post what it is after about 20 minutes of running? It should normalize after awhile. Thanks!
