### ISSUE TITLE
rewardRecipients .. no pool fees

### ISSUE THREAD

**Issue by megacrypto** [joshuayabut/z-nomp#16]
how do you set the rewardRecipients?

i added

>     "rewardRecipients": {
> 	"t1LVRY9TDBrZmagZ43oUVAJnnmKRUJykiEx": 1
>     },

but still says no pool fee:

> 2016-11-29 14:47:45 [Pool]      [zcash] (Thread 1) Stratum Pool Server Started for zcash [ZEC] {equihash}
>                                                 Network Connected:      Mainnet
>                                                 Detected Reward Type:   POW
>                                                 Current Block Height:   18814
>                                                 Current Block Diff:     702279.73609124
>                                                 Current Connect Peers:  8
>                                                 Network Difficulty:     670838.41605654
>                                                 Network Hash Rate:      37.95 MH
>                                                 Stratum Port(s):        3333
>                                                 Pool Fee Percent:       0%
>                                                 Block polling every:    30 ms
>

and 

> 2016-11-29 14:47:46 [Pool]      [zcash] (Thread 2) No rewardRecipients have been setup which means no fees will be taken

**Comment by joshuayabut** [comment]
Reward recipients aren't working at the moment. I'll work on this over the weekend.

**Comment by sennevb** [comment]
@joshuayabut got a fix allready??

**Comment by joshuayabut** [comment]
Yup! Be sure to do a "git pull; npm update; npm install" to get the latest code.

https://github.com/joshuayabut/node-stratum-pool/commit/48ea6acf04bb4ca74e4356bd324bc53b34a94e0f
