### ISSUE TITLE
E0078: RPC method did not return 200 OK: Address: t1b8dTy7cYGNCCVa3YhHXDkspWdera1tq7a ERROR: RPC call did not return 200: HTTP error: 500 - JSON Response: [-4] Insufficient funds, coinbase funds can only be spent after they have been sent to a zaddr

### ISSUE THREAD

**Issue by coolsd** [joshuayabut/z-nomp#25]
Zclassic  pool 

{
    "walletversion" : 60000,
    "balance" : 301.99145731,
    "unconfirmed_balance" : 0.00000000,
    "immature_balance" : 62.50032672,
    "txcount" : 653,
    "keypoololdest" : 1480675681,
    "keypoolsize" : 101
}

E0078: RPC method did not return 200 OK: Address: t1b8dTy7cYGNCCVa3YhHXDkspWdera1tq7a ERROR: RPC call did not return 200: HTTP error: 500 - JSON Response: [-4] Insufficient funds, coinbase funds can only be spent after they have been sent to a zaddr

**Comment by aayanl** [comment]
are you using two different taddresses in your config file?

**Comment by coolsd** [comment]
Is the same taddresses

**Comment by joshuayabut** [comment]
You'll need to put two different T-addresses for it to work correctly due to coinbase rewards needing to goto a Z-address first.

**Comment by coolsd** [comment]
https://classic.zcha.in/blocks/0000001a4f8e401596d2b84c81555be31933325803c3424d4954fb7c7d7a76eb

Why mining is only 12ZCL

**Comment by aayanl** [comment]
Made a new issue for the incomplete payment #32
