### ISSUE TITLE
Payments aren't going through, NOMP still thinks blocks are still pending

### ISSUE THREAD

**Issue by aayanl** [joshuayabut/z-nomp#3]
Title, I had a block on testnet have 222 confirms, I checked that the block reward was going to the correct address and it was, but the address I set for it to pay never had any zct come

**Comment by lutsifer** [comment]
HEY :)
I have zero instance. It was working great for 4 days. Then suddenly this morning I had two blocks stuck on *pending* even if the explorer was showing more then 20 30 confirmations. I did restart and it seems this helped somehow.  Then again about an hour ago I got two blocks again permanent pending. Now I got third... and somehow this third cleared the issue with the previous...
Any thoughts about this?

**Comment by lutsifer** [comment]
I forget to say - nothing suspicious anywhere. Only this payment warning here:
 Error sending payments {"code":-6,"message":"Insufficient funds, coinbase funds can only be spent after they have been sent to a zaddr"}
Payment actually works well on the next turns when receive more money from the z-addr.

**Comment by lutsifer** [comment]
Also I receive the immature coins for the block (as normally should be. The only thing is this pending label.
