### ISSUE TITLE
Coinbase only rewards 12 ZCL for some people

### ISSUE THREAD

**Issue by aayanl** [joshuayabut/z-nomp#32]
https://classic.zcha.in/blocks/0000002a445b2cd450ac930275ba4b597680ba49814659af8debbcf71def388e

**Comment by aayanl** [comment]
@coolsd, have you made any changes to the zcash daemon?

**Comment by coolsd** [comment]
no change.

**Comment by aayanl** [comment]
Doesn't affect zcash

**Comment by joshuayabut** [comment]
I'm going to review node-stratum since this bug would come from there.

**Comment by joshuayabut** [comment]
Should be fixed now.... There was an issue with BigNum losing precision so I've set the blockReward calculations to use native JS as a fix.

https://github.com/joshuayabut/node-stratum-pool/commit/41d082e9021afa7844421ec5f29663548a9305ae
