### ISSUE TITLE
equihashverify node 0.10 issue

### ISSUE THREAD

**Issue by ddobreff** [joshuayabut/z-nomp#41]
Hi, I have an issue installing latest build due to this package not compatible with nodejs v0.10

> equihashverify@0.0.1 install /home/zcash/.npm/equihashverify/0.0.1/package
> node-gyp rebuild

make: Entering directory `/home/zcash/.npm/equihashverify/0.0.1/package/build'
  CC(target) Release/obj.target/libequi/src/equi/equi.o
../src/equi/equi.c: In function ‘isZero’:
../src/equi/equi.c:78:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < len; i++) {
                     ^
  CC(target) Release/obj.target/libequi/src/equi/endian.o
  SOLINK(target) Release/obj.target/equi.so
  SOLINK(target) Release/obj.target/equi.so: Finished
  COPY Release/lib.target/equi.so
  CXX(target) Release/obj.target/equihashverify/equihashverify.o
../equihashverify.cc:14:19: error: ‘FunctionCallbackInfo’ in namespace ‘v8’ does not name a type
 void Verify(const v8::FunctionCallbackInfo<Value>& args) {
                   ^
../equihashverify.cc:14:23: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
 void Verify(const v8::FunctionCallbackInfo<Value>& args) {
                       ^
../equihashverify.cc:14:43: error: expected ‘,’ or ‘...’ before ‘<’ token
 void Verify(const v8::FunctionCallbackInfo<Value>& args) {
                                           ^
../equihashverify.cc: In function ‘void Verify(int)’:
../equihashverify.cc:16:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
   HandleScope scope(isolate);
                            ^
../equihashverify.cc:16:28: note: candidates are:
In file included from /home/zcash/.node-gyp/0.10.25/src/node.h:62:0,
                 from ../node_modules/nan/nan.h:47,
                 from ../equihashverify.cc:1:
/home/zcash/.node-gyp/0.10.25/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
   HandleScope(const HandleScope&);
   ^
/home/zcash/.node-gyp/0.10.25/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/home/zcash/.node-gyp/0.10.25/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
   HandleScope();
   ^
/home/zcash/.node-gyp/0.10.25/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../equihashverify.cc:18:7: error: ‘args’ was not declared in this scope
   if (args.Length() < 2) {
       ^
../equihashverify.cc:19:12: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
   isolate->ThrowException(Exception::TypeError(

**Comment by aayanl** [comment]
z-nomp is only compatible with node 7.2.0
