### ISSUE TITLE
Add support for europecoin: algorithm "1GB AES Pattern Search POW" (20.00 usd) 

### ISSUE THREAD

**Issue by teosanru** [joshuayabut/z-nomp#47]
Hello, I want to mount my pool of europecoin, but there is still no support in unomp for this currency crypto, could you please. Make the adjustments, I am willing to pay 20.00 USD when the work is done

**Comment by aayanl** [comment]
Currently z-nomp only supports equihash coins. You can copy a x11 coin from unomp's coins/ and have fit europecoin's paramaters

**Comment by teosanru** [comment]
Europècoin, is not x11, now has another algorithm: "1GB AES Pattern Search POW" could you help me?

**Comment by joshuayabut** [comment]
Hi non-equihash coins are beyond the scope of this project. Lots of changes were made with node-stratum-pool so it's currently not possible without a significant amount of rework.
