### ISSUE TITLE
merged mining

### ISSUE THREAD

**Issue by sennevb** [joshuayabut/z-nomp#48]
hi,

Isnt their a possibility to do some kind of merged mining, since the algo (zcash and zclassic) is same??

Greetings,

Senne

**Comment by aayanl** [comment]
Merge mining is a bit complex than that. The coin needs to support AuxPoW which means it can accept a valid PoW from another chain regardless of difficulty. That requires a hardfork

**Comment by aayanl** [comment]
You can leave this as a suggestion at the zclassic github
