### ISSUE TITLE
0 ksol hashrate

### ISSUE THREAD

**Issue by sennevb** [joshuayabut/z-nomp#50]
wrong calculation i guess, see screenshot
![image](https://cloud.githubusercontent.com/assets/6636264/21471371/c7eca3a8-cab0-11e6-975f-12a6f92acbb7.png)

**Comment by joshuayabut** [comment]
I rewrote the calculation.. can you give it a try? Thanks!

https://github.com/joshuayabut/z-nomp/commit/03e8e3af1d9be51a2405fbcd6e9789b4f2d8f0ed

**Comment by sennevb** [comment]
will do, gimme sec

**Comment by sennevb** [comment]
seems to work on graph's , only on mainpage and worker stats it gives other values

**Comment by sennevb** [comment]
![image](https://cloud.githubusercontent.com/assets/6636264/21472809/5c62dc1c-caea-11e6-81ed-83179334732d.png)
![image](https://cloud.githubusercontent.com/assets/6636264/21472814/6f0099a4-caea-11e6-8eb6-15df68931efe.png)
![image](https://cloud.githubusercontent.com/assets/6636264/21472818/813af07e-caea-11e6-8217-b068041fe227.png)

**Comment by joshuayabut** [comment]
Ok can you try doing:

```
git reset HEAD~1
git pull
npm start
```
Thanks!

**Comment by joshuayabut** [comment]
Works fine as of https://github.com/joshuayabut/z-nomp/commit/c83ed0704940b9e712eef1deaff7108c1444e864

**Comment by sennevb** [comment]
after git pull i get:
Unpacking objects: 100% (7/7), done.
From https://github.com/joshuayabut/node-open-mining-portal
 + 03e8e3a...c83ed07 master     -> origin/master  (forced update)
 + 0dfd16a...7b840b2 movrcx-hp  -> origin/movrcx-hp  (forced update)
Updating c640b4f..c83ed07
error: Your local changes to the following files would be overwritten by merge:
        libs/stats.js
        website/static/stats.js
Please, commit your changes or stash them before you can merge.

stash??

**Comment by sennevb** [comment]
edit: removed the files and pulled it from git again

**Comment by sennevb** [comment]
can be closed, works now!
