### ISSUE TITLE
Not the right conclusion hashrate

### ISSUE THREAD

**Issue by innova-market** [joshuayabut/z-nomp#6]
I have shows 1.48 TH
![default](https://cloud.githubusercontent.com/assets/4079108/20533774/c10d4824-b0ef-11e6-97f0-4b2bec43418a.PNG)

![2](https://cloud.githubusercontent.com/assets/4079108/20533920/5cc8d12a-b0f0-11e6-8ee8-9c1096e3bb96.PNG)
![3](https://cloud.githubusercontent.com/assets/4079108/20535345/6ec2672e-b0f5-11e6-9306-8ddc77863d92.PNG)

**Comment by joshuayabut** [comment]
Confirmed. Will work this after fixing payment processing issues.

**Comment by joshuayabut** [comment]
Should be fixed now.
