### ISSUE TITLE
 help gather

### ISSUE THREAD

**Issue by kertis8763** [joshuayabut/z-nomp#60]
![pool](https://cloud.githubusercontent.com/assets/23327076/21684559/2a59324c-d36f-11e6-81c3-44d7e78e700c.png)

What you need to do next, do not judge strictly, I gather for the first time, if anyone has the detailed instruction will be grateful.

**Comment by sennevb** [comment]
please read, there is no pool config...

**Comment by aayanl** [comment]
No need for hostility, can you check if in your pool config, enabled is set to true?

**Comment by kertis8763** [comment]
everything is good, but how to install a pool if there is an instruction, help, will not stay in debt, with incomes for the first sacrifice zcash

**Comment by sennevb** [comment]
please post your pool config..

**Comment by kertis8763** [comment]
{
    "logLevel": "debug",
    "logColors": true,

    "cliPort": 17117,

    "clustering": {
        "enabled": true,
        "forks": "auto"
    },

    "defaultPoolConfigs": {
        "blockRefreshInterval": 30,
        "jobRebroadcastTimeout": 55,
        "connectionTimeout": 600,
        "emitInvalidBlockHashes": false,
        "validateWorkerUsername": true,
        "tcpProxyProtocol": false,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 500,
            "purgeInterval": 300
        },
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        }
    },

    "website": {
        "enabled": true,
        "host": "0.0.0.0",
        "port": 8080,
        "stratumHost": "cryppit.com",
        "stats": {
            "updateInterval": 30,
            "historicalRetention": 43200,
            "hashrateWindow": 300
        },
        "adminCenter": {
            "enabled": false,
            "password": "password"
        }

**Comment by kertis8763** [comment]
it is possible that something is not right, I never collected pull. writes that the posix module is not installed, what it could be, and a bit about the assembly of the swimming pool is not clear how to assemble

**Comment by kertis8763** [comment]
![pool2](https://cloud.githubusercontent.com/assets/23327076/21722478/e2d0c24e-d43d-11e6-878c-a2d9c794d2ff.png)

**Comment by kertis8763** [comment]
now he writes the following lines

**Comment by kertis8763** [comment]
this file zcash.conf

{
    "enabled": true,
    "coin": "zcash.json",

    "address": "",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 10,

    "rewardRecipients": {
        "": 0.2,
        "": 0.3
    },

    "paymentProcessing": {
        "enabled": false,
        "paymentInterval": 20,
        "minimumPayment": 0.1,
        "daemon": {
            "host": "127.0.0.1",
            "port": 19332,
            "user": "boxer377",
            "password": "k1e4r7tis"
        }
    },

    "ports": {
        "3032": {
            "diff": 0.05,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 8232,
            "user": "boxer377",
            "password": "k1e4r7tis"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zec",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by kertis8763** [comment]
I and my friends have mining rigs, wanted to assemble a pool of associations, can provide remote access to help, if I can throw in a little bit of coins

**Comment by sennevb** [comment]
Website: fill in up or hostname instead of 0.0.0.0

You haven't filled in your zcash adressen, please make some adresses first and fill them in.

Am not at home atm, when i do i can have a look from remote (in30mins i guess)

**Comment by kertis8763** [comment]
does not go out, sennevb write on skype nick angerfist872 as will be free time, I will provide remote access as the first coin earn, share

**Comment by sennevb** [comment]
if you still need help, i'm at home, send me an email with teamviewer credentials:
sennevanbaelen@gmail.com

**Comment by sennevb** [comment]
![image](https://cloud.githubusercontent.com/assets/6636264/21725367/6b82f2a2-d438-11e6-88d0-0bdb47f07f8f.png)

@aayanl i helped him wit hsetting up, he used wrong port.
but now we have this erro and havent seen those..

**Comment by kertis8763** [comment]
![pool3](https://cloud.githubusercontent.com/assets/23327076/21726240/fa524c3a-d44c-11e6-941c-4c8cd4a0c56b.png)


help, who encountered such a problem that occurs

**Comment by aayanl** [comment]
remove the empty reward recipients

**Comment by aayanl** [comment]
also keep the website host at 0.0.0.0, it will bind to all available IP hosts.

**Comment by kertis8763** [comment]
nothing has changed, maybe I'm doing something wrong

**Comment by aayanl** [comment]
possibility related to #61

**Comment by joshuayabut** [comment]
The invalid checksum means that you have an incorrect address loaded somewhere.

**Comment by kertis8763** [comment]
Thank you collected. Now I can not find how to generate addresses for zclassic, maybe someone had experience.

**Comment by sennevb** [comment]
I generated for you and put them in the .Conf.. it should work

**Comment by kertis8763** [comment]
For zclassic use the same address that you have created?

**Comment by sennevb** [comment]
i created all the adresses for you on the teamviewer, why do you need to change them??

**Comment by kertis8763** [comment]
I thought they just default were to zcl

**Comment by sennevb** [comment]
no :-/ there is no default adress in the conf.. is pool not working or why are you changing it??

**Comment by kertis8763** [comment]
Pool work will soon join friends in the pool, just decided to add zcl

**Comment by sennevb** [comment]
ah you mean zclassic
i dunno i added adresses for them lol :-D think only zcash

What is port problem now on your router??

**Comment by kertis8763** [comment]
but gives an error message, I am now trying to finalize)

**Comment by sennevb** [comment]
you must make adresses for zclassic

**Comment by kertis8763** [comment]
on github I have not found how to generate addresses zcl

**Comment by sennevb** [comment]
https://github.com/zcash/zcash/wiki/1.0-User-Guide

**Comment by kertis8763** [comment]
and if generate new keys, then zcash is turned off?

**Comment by aayanl** [comment]
no, the pool software needs the zcash daemon to be on

**Comment by kertis8763** [comment]
![image](https://cloud.githubusercontent.com/assets/23327076/21955033/88ad4302-da7b-11e6-92d5-d02b9d0146d6.png)

**Comment by kertis8763** [comment]
![image](https://cloud.githubusercontent.com/assets/23327076/21955039/9be0fba8-da7b-11e6-9d16-0550f01b9845.png)

**Comment by kertis8763** [comment]
There seems necessary to reassign the port? Where to do it and can give that something else did not complete?

**Comment by sennevb** [comment]
Zclassic.json

**Comment by kertis8763** [comment]
{
    "enabled": false,
    "coin": "zclassic.json",

    "address": "t1cTXjzRMif37uWZfy66fnDpZ1UELz6mV4h",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zc9P1jo2SAirFpa6noHd5FeYryfY8nKbM4sYC3udZ6SnVZC1PeLKdd6oZf1XDh4fx8KhPeCvCnbJv8eBWS1BzvNBsHfjeNi",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1dNCJUT8634tGVZ7MxyNEYPfSG1jfZn69X",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 10,

    

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 0.5,
        "daemon": {
            "host": "127.0.0.1",
            "port": 12177,
            "user": "boxer377",
            "password": "k1e4r7tis"
        }
    },

    "ports": {
        "3032": {
            "diff": 0.05,
            "varDiff": {
                "minDiff": 0.04,
                "maxDiff": 16,
                "targetTime": 15,
                "retargetTime": 60,
                "variancePercent": 30
            }
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 12177,
            "user": "boxer377",
            "password": "k1e4r7tis"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "zcl",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}





in the Enable write true

**Comment by aayanl** [comment]
Your enabled needs to be true

**Comment by aayanl** [comment]
Since this is a configuration issue, I'm closing it, but we are still happy to help
