### ISSUE TITLE
mpos for z-nomp

### ISSUE THREAD

**Issue by ceozero** [joshuayabut/z-nomp#65]
Where is the MPOs configuration file. I can't display the block, height, difficulty in mpos.
thank u

**Comment by ceozero** [comment]
Where can I delete the history data of z-nomp.

**Comment by kertis8763** [comment]
It seems there is no

**Comment by ceozero** [comment]
@kertis8763 oh my god...

**Comment by kertis8763** [comment]
z-nomp/libs/mposCompatibility.js

**Comment by kertis8763** [comment]
@ceozero вася

**Comment by aayanl** [comment]
in you coin config fill, there's a mpos section there, mpos hasn't been officially tested though

**Comment by aayanl** [comment]
#2
