### ISSUE TITLE
auto pay bug.

### ISSUE THREAD

**Issue by ceozero** [joshuayabut/z-nomp#69]
![image](https://cloud.githubusercontent.com/assets/22513657/22108061/4571a4ce-de8c-11e6-9e8b-98440d597fc8.png)

Automatic payment is not only the use of "tAddress": the address of the coin, the use of the entire wallet all the addresses of coins. This will cause a very confusing situation.
 I think we should use z_sendmany...  you see!

**Comment by aayanl** [comment]
This is the intended purpose, payments are done with sendmany but the coin cycling is done with z_sendmany, it's highly recommended to use a separate daemon for z_sendmany. Ill look into adding z_sendmany for payments
