### ISSUE TITLE
What does this error?

### ISSUE THREAD

**Issue by kertis8763** [joshuayabut/z-nomp#70]
![image](https://cloud.githubusercontent.com/assets/23327076/22160477/105a2ef4-df5f-11e6-96a6-ba696165cd23.png)

**Comment by kertis8763** [comment]
There are no miners, so this error occurs?

**Comment by aayanl** [comment]
Your pool can't connect to the zcash daemon

**Comment by kertis8763** [comment]
How to fix the error?

**Comment by sennevb** [comment]
restart demaon or check the .Conf regarding your connection
