### ISSUE TITLE
Administration Panel Need Help!

### ISSUE THREAD

**Issue by Aleix-Oto** [joshuayabut/z-nomp#74]
I installed correctly but where can i get a sql sample for create database??

admin panel dont work for me, im login succesefull but can't enter in Administration options website

need a sql database???? where can i get it?

thanks
[http://minergpu.com](url)

**Comment by aayanl** [comment]
z-nomp uses redis, you can access the admin page at /admin but it's lackluster. An admin page isn't needed since z-nomp's frontend is stupidly simple
