### ISSUE TITLE
website can't initialize

### ISSUE THREAD

**Issue by cjcpro42** [joshuayabut/z-nomp#79]
Hi there, on our pool 1 server, z-nomp, website and stats running fine. Pool 2 z-nomp states it's running and website started but not responding. Checked firewall everything is correct. Can anyone assist me with this. config.json file shows website is enabled and local host and port 8080. Everything matches as pool 1. Any ideas what to look at ?

**Comment by aayanl** [comment]
can you make sure the website host is on 0.0.0.0 instead of 127.0.0.1?
