### ISSUE TITLE
Add pool to README

### ISSUE THREAD

**Issue by hellcatz** [joshuayabut/z-nomp#80]
Zcash Pool http://luckpool.org Custom Frontend w/Miner's Jackpot

**Comment by Aleix-Oto** [comment]
Zcash Zclassic Pool https://www.minergpu.com

**Comment by aayanl** [comment]
minergpu seemed to be down so I didn't add it

**Comment by ceozero** [comment]
@hellcatz 
Unable to reject invalid share,
How to solve.
I saw
Http://luckpool.org also cannot deny invalid sharing.

**Comment by ceozero** [comment]
@hellcatz 
https://github.com/ceozero/equihashverify/commit/3c2cb9eb4334b4c7fa6714375a2cb62633a2d397


This is my fork, this coin can not accept zcash miners "find the block are orphans", but my pool can not refuse to share zcash miners.
