### ISSUE TITLE
is it support Zcoin/XZC?

### ISSUE THREAD

**Issue by saymissme** [joshuayabut/z-nomp#84]
Zcoin had founders reward,like zcash
XZC algo is lyra2Z begin block 20500
our z-nomp was support it?

**Comment by aayanl** [comment]
no, z-nomp will only support equihash currencies

**Comment by aayanl** [comment]
Ocminer has a fork of NOMP working for Zcoin's new algo https://github.com/ocminer/node-multi-hashing-xzc

**Comment by saymissme** [comment]
thx
my pool is running

**Comment by GianniExplore** [comment]
[zcoin] Cannot run a pool for unsupported algorithm "lyra2Z" 

what's wrong ?
coins/zcoin.json
{
    "name": "zcoin",
    "symbol": "xzc",
    "algorithm": "lyra2Z",
    "requireShielding": false
}

**install  https://github.com/ocminer/node-multi-hashing-xzc**
using npm 0.12.8

npm install multi-hashing

npm WARN package.json multi-hashing-test@0.0.9 No license field.
npm WARN cannot run in wd multi-hashing@0.0.4 node-gyp rebuild (wd=/home/user/z-nomp-zcoin/node-multi-hashing-xzc/node_modules/multi-hashing)
multi-hashing@0.0.4 node_modules/multi-hashing
└── bindings@1.2.1
